---
title: "ers_rural_dev"
format: html
---

```{r}
library(tidyverse)
logger::log_threshold(logger::DEBUG)
```

# RUC

Data file URLs have a portion `v=...` in the end (e.g. `https://ers.usda.gov/sites/default/files/_laserfiche/DataFiles/53251/Ruralurbancontinuumcodes2023.xlsx?v=31091`).
This portion is changes sometime when the page with links is refreshed, and the download works even without it.

2023 data is available in two formats, XLSX and CSV.
We use XLSX format because it has the same structure as all previous years.
CSV is in long form.


```{r}

ers_rural_get("ruc_1974")

```


# UI

[Data](https://www.ers.usda.gov/data-products/urban-influence-codes)
[Documentation](https://www.ers.usda.gov/data-products/urban-influence-codes/documentation)

```{r}
# download all raw files
get("ers_rural", "raw_ui_2003pr")
get("ers_rural", "raw_ui_2003_1993")
get("ers_rural", "raw_ui_2013")
get("ers_rural", "raw_ui_2024")

# get all tables bypassing cache
ers_rural_get("ui_2003pr")
ers_rural_get("ui_2003_1993")
ers_rural_get("ui_2013")
ers_rural_get("ui_2024")

get("ers_rural", "ui_2003pr")
get("ers_rural", "ui_2003_1993")
get("ers_rural", "ui_2013")
get("ers_rural", "ui_2024")

```


# RUCA

[Data](https://www.ers.usda.gov/data-products/rural-urban-commuting-area-codes)

```{r}
# download all raw files
ls("ers_rural", "raw_ruca") |>
  purrr::map(\(x) get("ers_rural", x))


# get all tables bypassing cache
ers_rural_get("ruca_1990")
ers_rural_get("ruca_2000")
ers_rural_get("ruca_2010")
ers_rural_get("ruca_2010zip")
ers_rural_get("ruca_2020")
ers_rural_get("ruca_2020zip")

c("ruca_1990", "ruca_2000", "ruca_2010", "ruca_2010zip", "ruca_2020", "ruca_2020zip") |>
  purrr::map(\(x) get("ers_rural", x))

```

# FAR

[Data](https://www.ers.usda.gov/data-products/frontier-and-remote-area-codes)


```{r}
get("ers_rural", "raw_far_2000")
get("ers_rural", "raw_far_2010")

ers_rural_get("far_2000")
ers_rural_get("far_2010")

get("ers_rural", "far_2000")
get("ers_rural", "far_2010")

```


