collection: chrr
desc: County Health Rankings and Roadmaps (CHRR)
urls:
  "Home":
    "https://www.countyhealthrankings.org/"
  "Data Files":
    "https://www.countyhealthrankings.org/health-data/methodology-and-sources/data-documentation"
  "Methods":
    "https://www.countyhealthrankings.org/health-data/methodology-and-sources/methods"



data:
  # ---- Annual Analytic Data files
  raw_2025:
    desc: 2025 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2025.csv
    url: https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2025_v3.csv
  raw_2024:
    desc: 2024 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2024.csv
    url: https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2024.csv
  raw_2023:
    desc: 2023 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2023.csv
    url: https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2023_0.csv
  raw_2022:
    desc: 2022 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2022.csv
    url: https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2022.csv
  raw_2021:
    desc: 2021 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2021.csv
    url: https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2021.csv
  raw_2020:
    desc: 2020 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2020.csv
    url: https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2020_0.csv
  raw_2019:
    desc: 2019 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2019.csv
    url: https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2019.csv
  raw_2018:
    desc: 2018 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2018.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2018_0.csv
  raw_2017:
    desc: 2017 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2017.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2017.csv
  raw_2016:
    desc: 2016 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2016.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2016.csv
  raw_2015:
    desc: 2015 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2015.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2015.csv
  raw_2014:
    desc: 2014 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2014.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2014.csv
  raw_2013:
    desc: 2013 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2013.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2013.csv
  raw_2012:
    desc: 2012 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2012.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2012.csv
  raw_2011:
    desc: 2011 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2011.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2011.csv
  raw_2010:
    desc: 2010 County Health Rankings Analytic Data
    type: raw
    path: raw/analytic/2010.csv
    url: https://www.countyhealthrankings.org/sites/default/files/analytic_data2010.csv



  "2025": &analytic_2025
    mask: "{year}"
    desc: "{year} County Health Rankings Analytic Data"
    type: table
    path: "proc/analytic/{year}.pq"
    depends: "raw_{year}"
    schema:
      statecode:
        desc: State FIPS Code
        type: character
      countycode:
        desc: County FIPS Code
        type: character
      fipscode:
        desc: 5-digit FIPS Code
        type: character
      state:
        desc: State Abbreviation
        type: character
      county:
        desc: Name
        type: character
      year:
        desc: Release Year
        type: integer
      county_clustered:
        desc: County Clustered (Yes=1/No=0)
        type: integer
      variable:
        desc: Variable name, starting with "vXXX_"
        type: character
      description:
        desc: Description of variable
        type: character
      value:
        desc: Value of variable
        type: double

  "2024": *analytic_2025

  "2023": &analytic_2023
    mask: "{year}"
    desc: "{year} County Health Rankings Analytic Data"
    type: table
    path: "proc/analytic/{year}.pq"
    depends: "raw_{year}"
    schema:
      statecode:
        desc: State FIPS Code
        type: character
      countycode:
        desc: County FIPS Code
        type: character
      fipscode:
        desc: 5-digit FIPS Code
        type: character
      state:
        desc: State Abbreviation
        type: character
      county:
        desc: Name
        type: character
      year:
        desc: Release Year
        type: integer
      county_ranked:
        desc: County Ranked (Yes=1/No=0)
        type: character
      variable:
        desc: Variable name, starting with "vXXX_"
        type: character
      description:
        desc: Description of variable
        type: character
      value:
        desc: Value of variable
        type: double

  "2022": *analytic_2023
  "2021": *analytic_2023
  "2020": *analytic_2023
  "2019": *analytic_2023
  "2018": *analytic_2023
  "2017": *analytic_2023
  "2016": *analytic_2023
  "2015": *analytic_2023
  "2014": *analytic_2023
  "2013": *analytic_2023
  "2012": *analytic_2023
  "2011": *analytic_2023
  "2010": *analytic_2023
