collection: nass
desc: National Agricultural Statistics Service (NASS)
urls:
  "Home":
    "https://www.nass.usda.gov/index.php"
  "Data Files":
    "https://www.nass.usda.gov/datasets/"
  "QuickStats":
    "https://quickstats.nass.usda.gov/"
  "QuickStats API":
    "https://quickstats.nass.usda.gov/api"



data:
  raw_census_2022: &raw_census
    mask: "raw_census_{year}"
    desc: Census of Agriculture, {year}
    type: raw
    path: raw/census/qs.census{year}.txt.gz
    url: https://www.nass.usda.gov/datasets/qs.census{year}.txt.gz
  raw_census_2017: *raw_census
  raw_census_2012: *raw_census
  raw_census_2007: *raw_census
  raw_census_2002: *raw_census

  census_2022: &census
    mask: "census_{year}"
    desc: "Census of Agriculture, {year}"
    type: table
    path: proc/census/{year}.pq
    depends: "raw_census_{year}"
    schema:
      source_desc:
          desc: Source of data (CENSUS or SURVEY). Census program includes the Census  of Ag as well as follow up projects. Survey program includes national, state,  and county surveys.
          type: character
      sector_desc:
          desc: Five high  level, broad categories useful to narrow down choices (Crops, Animals & Products, Economics,  Demographics, and Environmental).
          type: character
      group_desc:
          desc: Subsets within sector (e.g., under sector = Crops, the groups are Field  Crops, Fruit & Tree Nuts, Horticulture, and Vegetables).
          type: character
      commodity_desc:
          desc: The primary subject of interest (e.g., CORN, CATTLE, LABOR, TRACTORS,  OPERATORS).
          type: character
      class_desc:
          desc: Generally a physical attribute (e.g., variety, size, color, gender)  of the commodity.
          type: character
      prodn_practice_desc:
          desc: A method of production or action taken on the commodity (e.g., IRRIGATED,  ORGANIC, ON FEED).
          type: character
      util_practice_desc:
          desc: Utilizations (e.g., GRAIN, FROZEN, SLAUGHTER) or marketing channels  (e.g., FRESH MARKET, PROCESSING, RETAIL).
          type: character
      statisticcat_desc:
          desc: The aspect of a commodity being measured (e.g., AREA HARVESTED, PRICE  RECEIVED, INVENTORY, SALES).
          type: character
      unit_desc:
          desc: The unit associated with the statistic category (e.g., ACRES, $ / LB,  HEAD, $, OPERATIONS).
          type: character
      short_desc:
          desc: "A concatenation of six columns: commodity_desc, class_desc,  prodn_practice_desc, util_practice_desc, statisticcat_desc, and unit_desc."
          type: character
      domain_desc:
          desc: Generally another characteristic of operations that produce a  particular commodity (e.g., ECONOMIC CLASS, AREA OPERATED, NAICS  CLASSIFICATION, SALES). For chemical usage data, the domain describes the  type of chemical applied to the commodity. The domain = TOTAL will have no  further breakouts; i.e., the data value pertains completely to the  short_desc.
          type: character
      domaincat_desc:
          desc: Categories or partitions within a domain (e.g., under domain = Sales, domain categories include  $1,000 TO $9,999, $10,000 TO $19,999, etc).
          type: character
      agg_level_desc:
          desc: Aggregation level or geographic granularity of the data (e.g., State, Ag District, County, Region, Zip Code).
          type: character
      state_ansi:
          desc: American National Standards Institute (ANSI) standard 2-digit state  codes.
          type: character
      state_fips_code:
          desc: NASS 2-digit state codes; include 99 and 98 for US TOTAL and OTHER  STATES, respectively; otherwise match ANSI codes.
          type: character
      state_alpha:
          desc: State abbreviation, 2-character alpha code.
          type: character
      state_name:
          desc: State full name.
          type: character
      asd_code:
          desc: NASS defined county groups, unique within a state, 2-digit ag  statistics district code.
          type: character
      asd_desc:
          desc: Ag statistics district name.
          type: character
      county_ansi:
          desc: ANSI standard 3-digit county codes.
          type: character
      county_code:
          desc: NASS 3-digit county codes; includes 998 for OTHER (COMBINED) COUNTIES  and Alaska county codes; otherwise match ANSI codes.
          type: character
      county_name:
          desc: County name.
          type: character
      region_desc:
          desc: NASS defined geographic entities not readily defined by other  standard geographic levels. A region can be a less than a state (Sub-State) or a group of states (Multi-State), and may be specific to  a commodity.
          type: character
      zip_5:
          desc: US Postal Service 5-digit zip code.
          type: character
      watershed_code:
          desc: US Geological Survey (USGS) 8-digit Hydrologic Unit Code (HUC) for  watersheds.
          type: character
      watershed_desc:
          desc: Name assigned to the HUC.
          type: character
      congr_district_code:
          desc: US Congressional District 2-digit code.
          type: character
      country_code:
          desc: US Census Bureau, Foreign Trade Division 4-digit country code, as of  April, 2007.
          type: character
      country_name:
          desc: Country name.
          type: character
      location_desc:
          desc: Full description for the location dimension.
          type: character
      year:
          desc: The numeric year of the data.
          type: integer
      freq_desc:
          desc: Length of time covered (Annual,  Season, Monthly, Weekly, Point in Time). Monthly often covers more than one month. Point in Time is as of a particular  day.
          type: character
      begin_code:
          desc: If applicable, a 2-digit code corresponding to the beginning of the  reference period (e.g., for freq_desc = Monthly,  begin_code ranges from 01 (January) to 12 (December)).
          type: character
      end_code:
          desc: If applicable, a 2-digit code corresponding to the end of the  reference period (e.g., the reference period of Jan thru Mar will have begin_code = 01 and end_code = 03).
          type: character
      reference_period_desc:
          desc: The specific time frame, within a freq_desc.
          type: character
      week_ending:
          desc: Week ending date, used when freq_desc = Weekly.
          type: character
      load_time:
          desc: Date and time indicating when record was inserted into Quick Stats  database.
          type: character
      value:
          desc: Published data value.
          type: double
      value_f:
          desc: "VALUE suppression reason code: (D), (X) or (Z)."
          type: character
      cv_%:
          desc: Coefficient of variation. Available for the 2012 Census of Agriculture only. County-level CVs are generalized.
          type: double
      cv_%_f:
          desc: "CV_% suppression reason code: (D), (H) or (L)."
          type: character
  census_2017: *census
  census_2012: *census
  census_2007: *census
  census_2002: *census
