project:
  type: website
  render:
    - index.ipynb
    - naics.ipynb
    - geography.ipynb
    - geography_cbsa.ipynb
    - bea_io.ipynb
  post-render: touch _site/.nojekyll

website:
  title: "Public data"
  navbar:
    background: primary
    left:
      - text: Home
        href: index.ipynb
      - naics.ipynb
      - text: Geography
        menu:
          - geography.ipynb
          - text: CBSA
            href: geography_cbsa.ipynb
      - text: Input-Output
        menu:
          - text: Tables
            href: bea_io.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



