collection: ers_rural
desc: Rurality classifications from the USDA Economic Research Service (ERS)
urls:
  "Home":
    https://www.ers.usda.gov/topics/rural-economy-population/rural-classifications/
  "Rural-Urban Continuum Codes":
    https://www.ers.usda.gov/data-products/rural-urban-continuum-codes/
  "Urban Influence Codes":
    https://www.ers.usda.gov/data-products/urban-influence-codes/
  "Rural-Urban Commuting Area Codes":
    https://www.ers.usda.gov/data-products/rural-urban-commuting-area-codes/
  "Frontier and Remote Area Codes":
    https://www.ers.usda.gov/data-products/frontier-and-remote-area-codes/


data:
  raw_ruc_2003:
    desc: 2003 Rural-Urban Continuum Codes
    type: raw
    path: raw/ruralurbancodes2003.xls
    url: https://ers.usda.gov/sites/default/files/_laserfiche/DataFiles/53251/ruralurbancodes2003.xls?v=30590

  raw_ruc_2023:
    desc: 2023 Rural-Urban Continuum Codes
    type: raw
    path: raw/Ruralurbancontinuumcodes2023.csv
    url: https://ers.usda.gov/sites/default/files/_laserfiche/DataFiles/53251/Ruralurbancontinuumcodes2023.csv?v=21666

  ruc_2003:
    mask: "ruc_{year}"
    desc: 2003 Rural-Urban Continuum Codes
    type: table
    path: proc/ruc_2003.pq
    depends: raw_ruc_2003
    schema:
      fips:
        desc: County FIPS Code
        orig: FIPS Code
        type: character
      state:
        desc: State abbreviation
        orig: State
        type: character
      county_name:
        desc: County Name
        orig: County Name
        type: character
      ruc_code_1993:
        desc: 1993 Rural-urban Continuum Code
        orig: 1993 Rural-urban Continuum Code
        type: character
      ruc_code_2003:
        desc: 2003 Rural-urban Continuum Code
        orig: 2003 Rural-urban Continuum Code
        type: character
      population_2000:
        desc: 2000 Population
        orig: "2000 Population "
        type: integer
      commute_pct:
        desc: Percent of workers in nonmetro counties commuting to central counties of adjacent metro areas
        orig: Percent of workers in nonmetro counties commuting to central counties of adjacent metro areas
        type: double
      ruc_desc_2003:
        desc: Description for 2003 codes
        orig: Description for 2003 codes
        type: character

  ruc_2023:
    mask: "ruc_{year}"
    desc: 2023 Rural-Urban Continuum Codes
    type: table
    path: proc/ruc_2023.pq
    depends: raw_ruc_2023
    schema:
      fips:
        desc: County FIPS code
        orig: FIPS
        type: character
      state:
        desc: State abbreviation
        orig: State
        type: character
      county_name:
        desc: County name
        orig: County_Name
        type: character
      attribute:
        desc: One of "Population_2020", "RUCC_2023" or "Description"
        orig: Attribute
        type: character
      value:
        desc: County value of a given attribute
        orig: Value
        type: character

