dataset: bea_io
description: Input-Output Tables, BEA
urls:
  "Home":
    https://www.bea.gov/data/industries/input-output-accounts-data
  "Current - Industry File Download":
    https://apps.bea.gov/iTable/?isuri=1&reqid=151&step=1
  "Historical Data Archive":
    https://apps.bea.gov/histdatacore/
  "Gross Domestic Product by Industry and Input-Output Statistics":
    https://apps.bea.gov/histdatacore/histChildLevels.html?HMI=8&oldDiv=Industry%20Accounts

data:
  raw_curr:
    type: raw
    path: raw/AllTablesSUP_curr.zip
    url: https://apps.bea.gov/industry/iTables%20Static%20Files/AllTablesSUP.zip
  raw_2023:
    type: raw
    path: raw/AllTablesSUP_2023.zip
    url: https://apps.bea.gov/HistDataCore/wwwroot/Releases/Industry/2023/GDP_by_Industry/Q2/Annual_September-28-2023/AllTablesSUP.zip
  raw_2022:
    type: raw
    path: raw/AllTablesSUP_2022.zip
    url: https://apps.bea.gov/HistDataCore/wwwroot/Releases/Industry/2022/GDP_by_Industry/Q2/Annual_September-29-2022/AllTablesSUP.zip

  curr_use_sec_2022: &curr_use_sec
    desc: Use table, year {year}, sector level, current revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "AllTablesSUP/Use_Tables_Supply-Use_Framework_2017-2022_Sector.xlsx"
      skip: 5
      rows: 29
      matrix: [17, 15]
    schema: &schema_sec
      row_code:
        desc: Row code - sector level commodity.
        type: string
      row_name:
        desc: Row description - sector level commodity.
        type: string
      col_code:
        desc: Column code - sector level industry.
        type: string
      col_name:
        desc: Column description - sector level industry.
        type: string
      value:
        desc: Value at the intersection of row and column.
        type: number
      core_matrix:
        desc: Whether value is part of the core commodity-industry matrix.
        type: bool
  curr_use_sec_2021: *curr_use_sec
  curr_use_sec_2020: *curr_use_sec
  curr_use_sec_2019: *curr_use_sec
  curr_use_sec_2018: *curr_use_sec
  curr_use_sec_2017: *curr_use_sec

  curr_use_sum_2022: &curr_use_sum
    desc: Use table, year {year}, summary level, current revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "AllTablesSUP/Use_Tables_Supply-Use_Framework_2017-2022_Summary.xlsx"
      skip: 5
      rows: 85
      matrix: [73, 71]
    schema: &schema_sum
      row_code:
        desc: Row code - summary level commodity.
        type: string
      row_name:
        desc: Row description - summary level commodity.
        type: string
      col_code:
        desc: Column code - summary level industry.
        type: string
      col_name:
        desc: Column description - summary level industry.
        type: string
      value:
        desc: Value at the intersection of row and column.
        type: number
      core_matrix:
        desc: Whether value is part of the core commodity-industry matrix.
        type: bool
  curr_use_sum_2021: *curr_use_sum
  curr_use_sum_2020: *curr_use_sum
  curr_use_sum_2019: *curr_use_sum
  curr_use_sum_2018: *curr_use_sum
  curr_use_sum_2017: *curr_use_sum

  curr_use_det_2017:
    desc: Use table, year {year}, detail level, current revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "AllTablesSUP/Use_SUT_Framework_2017_DET.xlsx"
      skip: 4
      rows: 413
      matrix: [402, 402]
    schema: &schema_det
      row_code:
        desc: Row code - detail level commodity.
        type: string
      row_name:
        desc: Row description - detail level commodity.
        type: string
      col_code:
        desc: Column code - detail level industry.
        type: string
      col_name:
        desc: Column description - detail level industry.
        type: string
      value:
        desc: Value at the intersection of row and column.
        type: number
      core_matrix:
        desc: Whether value is part of the core commodity-industry matrix.
        type: bool

  curr_sup_sec_2022: &curr_sup_sec
    desc: Supply table, year {year}, sector level, current revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "AllTablesSUP/Supply_Tables_2017-2022_Sector.xlsx"
      skip: 5
      rows: 20
      matrix: [17, 15]
    schema: *schema_sec
  curr_sup_sec_2021: *curr_sup_sec
  curr_sup_sec_2020: *curr_sup_sec
  curr_sup_sec_2019: *curr_sup_sec
  curr_sup_sec_2018: *curr_sup_sec
  curr_sup_sec_2017: *curr_sup_sec

  curr_sup_sum_2022: &curr_sup_sum
    desc: Supply table, year {year}, summary level, current revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "AllTablesSUP/Supply_Tables_2017-2022_Summary.xlsx"
      skip: 5
      rows: 76
      matrix: [73, 71]
    schema: *schema_sum
  curr_sup_sum_2021: *curr_sup_sum
  curr_sup_sum_2020: *curr_sup_sum
  curr_sup_sum_2019: *curr_sup_sum
  curr_sup_sum_2018: *curr_sup_sum
  curr_sup_sum_2017: *curr_sup_sum

  curr_sup_det_2017:
    desc: Supply table, year {year}, detail level, current revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "AllTablesSUP/Supply_2017_DET.xlsx"
      skip: 4
      rows: 405
      matrix: [402, 402]
    schema: *schema_det

  2023_use_sec_2022: &2023_use_sec
    desc: Use table, year {year}, sector level, 2023 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Use_Tables_Supply-Use_Framework_2017-2022_Sector.xlsx"
      skip: 5
      rows: 29
      matrix: [17, 15]
    schema: *schema_sec
  2023_use_sec_2021: *2023_use_sec
  2023_use_sec_2020: *2023_use_sec
  2023_use_sec_2019: *2023_use_sec
  2023_use_sec_2018: *2023_use_sec
  2023_use_sec_2017: *2023_use_sec

  2023_use_sum_2022: &2023_use_sum
    desc: Use table, year {year}, summary level, 2023 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Use_Tables_Supply-Use_Framework_2017-2022_Summary.xlsx"
      skip: 5
      rows: 85
      matrix: [73, 71]
    schema: *schema_sum
  2023_use_sum_2021: *2023_use_sum
  2023_use_sum_2020: *2023_use_sum
  2023_use_sum_2019: *2023_use_sum
  2023_use_sum_2018: *2023_use_sum
  2023_use_sum_2017: *2023_use_sum

  2023_use_det_2017:
    desc: Use table, year {year}, detail level, 2023 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Use_SUT_Framework_2017_DET.xlsx"
      skip: 4
      rows: 413
      matrix: [402, 402]
    schema: *schema_det

  2023_sup_sec_2022: &2023_sup_sec
    desc: Supply table, year {year}, sector level, 2023 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Supply_Tables_2017-2022_Sector.xlsx"
      skip: 5
      rows: 20
      matrix: [17, 15]
    schema: *schema_sec
  2023_sup_sec_2021: *2023_sup_sec
  2023_sup_sec_2020: *2023_sup_sec
  2023_sup_sec_2019: *2023_sup_sec
  2023_sup_sec_2018: *2023_sup_sec
  2023_sup_sec_2017: *2023_sup_sec

  2023_sup_sum_2022: &2023_sup_sum
    desc: Supply table, year {year}, summary level, 2023 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Supply_Tables_2017-2022_Summary.xlsx"
      skip: 5
      rows: 76
      matrix: [73, 71]
    schema: *schema_sum
  2023_sup_sum_2021: *2023_sup_sum
  2023_sup_sum_2020: *2023_sup_sum
  2023_sup_sum_2019: *2023_sup_sum
  2023_sup_sum_2018: *2023_sup_sum
  2023_sup_sum_2017: *2023_sup_sum

  2023_sup_det_2017:
    desc: Supply table, year {year}, detail level, 2023 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Supply_2017_DET.xlsx"
      skip: 4
      rows: 405
      matrix: [402, 402]
    schema: *schema_det

  2022_use_sec_2021: &2022_use_sec
    desc: Use table, year {year}, sector level, 2022 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Use_SUT_Framework_1997-2021_SECT.xlsx"
      skip: 5
      rows: 29
      matrix: [17, 15]
    schema: *schema_sec
  2022_use_sec_2020: *2022_use_sec
  2022_use_sec_2019: *2022_use_sec
  2022_use_sec_2018: *2022_use_sec
  2022_use_sec_2017: *2022_use_sec
  2022_use_sec_2016: *2022_use_sec
  2022_use_sec_2015: *2022_use_sec
  2022_use_sec_2014: *2022_use_sec
  2022_use_sec_2013: *2022_use_sec
  2022_use_sec_2012: *2022_use_sec
  2022_use_sec_2011: *2022_use_sec
  2022_use_sec_2010: *2022_use_sec
  2022_use_sec_2009: *2022_use_sec
  2022_use_sec_2008: *2022_use_sec
  2022_use_sec_2007: *2022_use_sec
  2022_use_sec_2006: *2022_use_sec
  2022_use_sec_2005: *2022_use_sec
  2022_use_sec_2004: *2022_use_sec
  2022_use_sec_2003: *2022_use_sec
  2022_use_sec_2002: *2022_use_sec
  2022_use_sec_2001: *2022_use_sec
  2022_use_sec_2000: *2022_use_sec
  2022_use_sec_1999: *2022_use_sec
  2022_use_sec_1998: *2022_use_sec
  2022_use_sec_1997: *2022_use_sec

  2022_use_sum_2021: &2022_use_sum
    desc: Use table, year {year}, summary level, 2022 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Use_SUT_Framework_1997-2021_SUM.xlsx"
      skip: 5
      rows: 85
      matrix: [73, 71]
    schema: *schema_sum
  2022_use_sum_2020: *2022_use_sum
  2022_use_sum_2019: *2022_use_sum
  2022_use_sum_2018: *2022_use_sum
  2022_use_sum_2017: *2022_use_sum
  2022_use_sum_2016: *2022_use_sum
  2022_use_sum_2015: *2022_use_sum
  2022_use_sum_2014: *2022_use_sum
  2022_use_sum_2013: *2022_use_sum
  2022_use_sum_2012: *2022_use_sum
  2022_use_sum_2011: *2022_use_sum
  2022_use_sum_2010: *2022_use_sum
  2022_use_sum_2009: *2022_use_sum
  2022_use_sum_2008: *2022_use_sum
  2022_use_sum_2007: *2022_use_sum
  2022_use_sum_2006: *2022_use_sum
  2022_use_sum_2005: *2022_use_sum
  2022_use_sum_2004: *2022_use_sum
  2022_use_sum_2003: *2022_use_sum
  2022_use_sum_2002: *2022_use_sum
  2022_use_sum_2001: *2022_use_sum
  2022_use_sum_2000: *2022_use_sum
  2022_use_sum_1999: *2022_use_sum
  2022_use_sum_1998: *2022_use_sum
  2022_use_sum_1997: *2022_use_sum

  2022_use_det_2012: &2022_use_det
    desc: Use table, year {year}, detail level, 2022 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Use_SUT_Framework_2007_2012_DET.xlsx"
      skip: 4
      rows: 416
      matrix: [405, 405]
    schema: *schema_det
  2022_use_det_2007: *2022_use_det

  2022_sup_sec_2021: &2022_sup_sec
    desc: Supply table, year {year}, sector level, 2022 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Supply_Tables_1997-2021_SEC.xlsx"
      skip: 5
      rows: 20
      matrix: [17, 15]
    schema: *schema_sec
  2022_sup_sec_2020: *2022_sup_sec
  2022_sup_sec_2019: *2022_sup_sec
  2022_sup_sec_2018: *2022_sup_sec
  2022_sup_sec_2017: *2022_sup_sec
  2022_sup_sec_2016: *2022_sup_sec
  2022_sup_sec_2015: *2022_sup_sec
  2022_sup_sec_2014: *2022_sup_sec
  2022_sup_sec_2013: *2022_sup_sec
  2022_sup_sec_2012: *2022_sup_sec
  2022_sup_sec_2011: *2022_sup_sec
  2022_sup_sec_2010: *2022_sup_sec
  2022_sup_sec_2009: *2022_sup_sec
  2022_sup_sec_2008: *2022_sup_sec
  2022_sup_sec_2007: *2022_sup_sec
  2022_sup_sec_2006: *2022_sup_sec
  2022_sup_sec_2005: *2022_sup_sec
  2022_sup_sec_2004: *2022_sup_sec
  2022_sup_sec_2003: *2022_sup_sec
  2022_sup_sec_2002: *2022_sup_sec
  2022_sup_sec_2001: *2022_sup_sec
  2022_sup_sec_2000: *2022_sup_sec
  2022_sup_sec_1999: *2022_sup_sec
  2022_sup_sec_1998: *2022_sup_sec
  2022_sup_sec_1997: *2022_sup_sec

  2022_sup_sum_2021: &2022_sup_sum
    desc: Supply table, year {year}, summary level, 2022 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Supply_Tables_1997-2021_SUM.xlsx"
      skip: 5
      rows: 76
      matrix: [73, 71]
    schema: *schema_sum
  2022_sup_sum_2020: *2022_sup_sum
  2022_sup_sum_2019: *2022_sup_sum
  2022_sup_sum_2018: *2022_sup_sum
  2022_sup_sum_2017: *2022_sup_sum
  2022_sup_sum_2016: *2022_sup_sum
  2022_sup_sum_2015: *2022_sup_sum
  2022_sup_sum_2014: *2022_sup_sum
  2022_sup_sum_2013: *2022_sup_sum
  2022_sup_sum_2012: *2022_sup_sum
  2022_sup_sum_2011: *2022_sup_sum
  2022_sup_sum_2010: *2022_sup_sum
  2022_sup_sum_2009: *2022_sup_sum
  2022_sup_sum_2008: *2022_sup_sum
  2022_sup_sum_2007: *2022_sup_sum
  2022_sup_sum_2006: *2022_sup_sum
  2022_sup_sum_2005: *2022_sup_sum
  2022_sup_sum_2004: *2022_sup_sum
  2022_sup_sum_2003: *2022_sup_sum
  2022_sup_sum_2002: *2022_sup_sum
  2022_sup_sum_2001: *2022_sup_sum
  2022_sup_sum_2000: *2022_sup_sum
  2022_sup_sum_1999: *2022_sup_sum
  2022_sup_sum_1998: *2022_sup_sum
  2022_sup_sum_1997: *2022_sup_sum

  2022_sup_det_2012: &2022_sup_det
    desc: Supply table, year {year}, detail level, 2022 revision
    mask: "{revision}_{table}_{level}_{year}"
    type: table
    path: proc/{revision}/{table}/{level}/{year}
    depends: raw_{revision}
    read:
      file: "Supply_2007_2012_DET.xlsx"
      skip: 4
      rows: 408
      matrix: [405, 405]
    schema: *schema_det
  2022_sup_det_2007: *2022_sup_det

  curr_naics:
    desc: I-O to NAICS-2017 crosswalk, current revision
    mask: "{revision}_naics"
    type: table
    path: proc/{revision}/naics.pq
    depends: raw_{revision}
    read:
      file: "AllTablesSUP/Supply_2017_DET.xlsx"
      skip: 5
      rows: 1017
    schema: &schema_naics
      sector:
        desc: I-O sector level code
        type: string
      summary:
        desc: I-O summary level code
        type: string
      u_summary:
        desc: I-O underlying summary level code
        type: string
      detail:
        desc: I-O detail level code
        type: string
      title:
        desc: I-O industry title
        type: string
      naics:
        desc: NAICS code
        type: string

  2023_naics:
    desc: I-O to NAICS-2017 crosswalk, 2023 revision
    mask: "{revision}_naics"
    type: table
    path: proc/{revision}/naics.pq
    depends: raw_{revision}
    read:
      file: "Supply_2017_DET.xlsx"
      skip: 5
      rows: 1017
    schema: *schema_naics

  2022_naics:
    desc: I-O to NAICS-2012 crosswalk, 2022 revision
    mask: "{revision}_naics"
    type: table
    path: proc/{revision}/naics.pq
    depends: raw_{revision}
    read:
      file: "Supply_2007_2012_DET.xlsx"
      skip: 5
      rows: 1020
    schema: *schema_naics
